/*
 * File: app/view/ContactDetail.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Payback.view.ContactDetail', {
    extend: 'Ext.form.Panel',
    alias: 'widget.ContactDetail',

    config: {
        autoDestroy: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Details'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'button',
                        id: 'cancelContact',
                        ui: 'decline',
                        text: 'Cancel'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        id: 'saveContact',
                        ui: 'confirm',
                        text: 'Save'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Prey Information',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Name',
                        name: 'name'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Email',
                        name: 'email'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Phone',
                        name: 'phone'
                    }
                ]
            }
        ]
    }

});