/*
 * File: app/view/DebtDetail.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Payback.view.DebtDetail', {
    extend: 'Ext.form.Panel',
    alias: 'widget.DebtDetail',

    config: {
        autoDestroy: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Details'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'button',
                        id: 'cancelDebt',
                        ui: 'decline',
                        text: 'Cancel'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        id: 'saveDebt',
                        ui: 'confirm',
                        text: 'Save'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Debt Information',
                items: [
                    {
                        xtype: 'selectfield',
                        label: 'Name',
                        name: 'person_id',
                        displayField: 'name',
                        store: 'People',
                        valueField: 'id'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Reason',
                        name: 'reason'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Amount',
                        name: 'amount'
                    },
                    {
                        xtype: 'datepickerfield',
                        label: 'Date',
                        name: 'date'
                    }
                ]
            }
        ]
    }

});