/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Payback.view.MainView', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.MainView',

    requires: [
        'Payback.view.Summary',
        'Payback.view.Debts',
        'Payback.view.Prey'
    ],

    config: {
        items: [
            {
                xtype: 'Summary',
                itemId: 'Summary',
                title: 'Summary',
                iconCls: 'info'
            },
            {
                xtype: 'Debts',
                itemId: 'Debt',
                title: 'Debts',
                iconCls: 'arrow_down'
            },
            {
                xtype: 'Prey',
                itemId: 'Prey',
                title: 'Prey',
                iconCls: 'team'
            }
        ],
        tabBar: {
            docked: 'bottom',
            itemId: 'mytabbar'
        },
        listeners: [
            {
                fn: 'onSummaryViewActivate',
                event: 'activate',
                delegate: '#Summary'
            },
            {
                fn: 'onPanelActivate',
                event: 'activate',
                delegate: '#Debt'
            },
            {
                fn: 'onPanelActivate1',
                event: 'activate',
                delegate: '#Prey'
            },
            {
                fn: 'onMytabbarActivetabChange',
                event: 'activetabchange',
                order: 'before',
                delegate: '#mytabbar'
            }
        ]
    },

    onSummaryViewActivate: function(container, newActiveItem, oldActiveItem, options) {

        //if(location.hash!="")
        //location.hash ="summary";
        //Payback.app.application.getController('Payback.controller.Summary').redirectTo('Summary');
    },

    onPanelActivate: function(container, newActiveItem, oldActiveItem, options) {
        //location.hash = 'debt';
        //Payback.app.application.getController('Payback.controller.Debt').redirectTo('Debt');
    },

    onPanelActivate1: function(container, newActiveItem, oldActiveItem, options) {
        //location.hash = 'prey';

        //Payback.app.application.getController('Payback.controller.Contact').redirectTo('Prey');
    },

    onMytabbarActivetabChange: function(tabbar, value, oldValue, options) {
        return false;
    }

});