/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Payback.view.MainView', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.MainView',

    requires: [
        'Payback.view.Summary',
        'Payback.view.Debts',
        'Payback.view.Prey'
    ],

    config: {
        items: [
            {
                xtype: 'Summary',
                itemId: 'Summary',
                title: 'Summary',
                iconCls: 'info'
            },
            {
                xtype: 'Debts',
                itemId: 'Debt',
                title: 'Debts',
                iconCls: 'arrow_down'
            },
            {
                xtype: 'Prey',
                itemId: 'Prey',
                title: 'Prey',
                iconCls: 'team'
            }
        ],
        tabBar: {
            docked: 'bottom'
        },
        listeners: [
            {
                fn: 'onSummaryViewShow',
                event: 'show',
                delegate: '#Summary'
            },
            {
                fn: 'onPanelShow',
                event: 'show',
                delegate: '#Debt'
            },
            {
                fn: 'onPanelShow1',
                event: 'show',
                delegate: '#Prey'
            }
        ]
    },

    onSummaryViewShow: function(component, options) {

        //if(location.hash!="")
        // location.hash ="";
    },

    onPanelShow: function(component, options) {
        //location.hash = 'Debt';
    },

    onPanelShow1: function(component, options) {
        //location.hash = 'Prey';
    }

});