/*
 * File: app/view/myContactListItem.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Payback.view.myContactListItem', {
    extend: 'Ext.Container',
    alias: 'widget.myContactListItem',

    config: {
        baseCls: 'x-data-item',
        cls: [
            'x-list-item'
        ],
        items: [
            {
                xtype: 'container',
                baseCls: 'x-list-item-label',
                itemId: 'contactListItemDetail',
                tpl: [
                    '<div>{name}  ${balance}<br>',
                    '{phone} {email} </div>'
                ],
                items: [
                    {
                        xtype: 'button',
                        docked: 'right',
                        hidden: true,
                        itemId: 'mybutton12',
                        ui: 'decline-round',
                        text: 'delete'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onContactDeleteButtonTap',
                event: 'tap',
                delegate: '#mybutton12'
            }
        ]
    },

    onContactDeleteButtonTap: function(button, e, options) {
        var dataview = this.up('dataview');

        dataview.getStore().remove(this.getRecord());
        dataview.getStore().sync();
    },

    updateRecord: function(newRecord, oldeRecord) {
        newRecord.getData(true);
        this.child('component').setData(newRecord.data);
    }

});