/*
 * File: app/view/PaymentDetail.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Payback.view.PaymentDetail', {
    extend: 'Ext.form.Panel',
    alias: 'widget.PaymentDetail',

    config: {
        autoDestroy: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                ui: 'light',
                title: 'Payment Details',
                items: [
                    {
                        xtype: 'button',
                        id: 'cancelPayment',
                        iconCls: 'icon-back',
                        iconMask: true,
                        text: 'Cancel'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        id: 'savePayment',
                        iconCls: 'icon-save',
                        iconMask: true,
                        text: 'save'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'numberfield',
                        itemId: 'mynumberfield1',
                        label: 'Amount',
                        labelAlign: 'top',
                        name: 'amount'
                    },
                    {
                        xtype: 'datepickerfield',
                        label: 'Date',
                        labelAlign: 'top',
                        name: 'date',
                        placeHolder: 'mm/dd/yyyy'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Notes',
                        labelAlign: 'top',
                        name: 'memo'
                    }
                ]
            },
            {
                xtype: 'hiddenfield',
                name: 'debt_id'
            }
        ],
        listeners: [
            {
                fn: 'onMynumberfield1Focus',
                event: 'focus',
                delegate: '#mynumberfield1'
            }
        ]
    },

    onMynumberfield1Focus: function(textfield, e, options) {

        //android work around to hide keyboard.
        if (Ext.os.is.Android)
        Ext.Viewport.element.on({tap:function(){
            var field = document.createElement('input');
            field.setAttribute('type', 'text');
            document.body.appendChild(field);

            setTimeout(function() {
                field.focus();  

                setTimeout(function() {
                    field.setAttribute('style', 'display:none;');
                    field.parentNode.removeChild(field);
                }, 100);
            }, 50);
        }, single:true});
    }

});