/*
 * File: app/view/PaymentDetail.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Payback.view.PaymentDetail', {
    extend: 'Ext.form.Panel',
    alias: 'widget.PaymentDetail',

    config: {
        autoDestroy: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Payment Details'
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'button',
                        id: 'cancelPayment',
                        ui: 'decline',
                        text: 'Cancel'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        id: 'savePayment',
                        ui: 'confirm',
                        text: 'Save'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Payment Information',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Amount',
                        name: 'amount'
                    },
                    {
                        xtype: 'datepickerfield',
                        label: 'Date',
                        name: 'date',
                        placeHolder: 'mm/dd/yyyy'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Memo',
                items: [
                    {
                        xtype: 'textareafield',
                        name: 'memo'
                    }
                ]
            },
            {
                xtype: 'hiddenfield',
                name: 'debt_id'
            }
        ]
    }

});