/*
 * File: app/view/Summary.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Payback.view.Summary', {
    extend: 'Ext.Container',
    alias: 'widget.Summary',

    config: {
        id: 'SummaryView',
        style: 'background:white;',
        layout: {
            type: 'fit'
        },
        scrollable: false,
        tpl: [
            ''
        ],
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Loanshark'
            },
            {
                xtype: 'image',
                style: 'background-size: auto 100%;background-position: center center;',
                src: 'resources/images/shark.gif',
                mode: 'background'
            },
            {
                xtype: 'component',
                docked: 'bottom',
                height: '2em',
                id: 'SummaryContents',
                tpl: [
                    '<center>You\'re Owed: {totalOwed}</center>'
                ]
            }
        ]
    }

});