/*
 * File: app/view/Sync.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Payback.view.Sync', {
    extend: 'Ext.Panel',
    alias: 'widget.sync',

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            //this may take longer then expected
                            Ext.getStore('People').sync();
                            Ext.getStore('Debts').sync();
                            Ext.getStore('Payments').sync();




                        },
                        cls: 'my-buttons',
                        id: 'syncButton',
                        iconCls: 'icon-sync',
                        iconMask: true,
                        text: 'Add Prey'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, event) {
                            Ext.io.User.getCurrent(
                            function(user){
                                user.logout();
                            } 
                            );
                            localStorage.clear();

                        },
                        cls: 'my-buttons',
                        id: 'logoutButton',
                        iconAlign: 'right',
                        iconCls: 'delete',
                        iconMask: true,
                        text: 'Add Prey'
                    }
                ]
            }
        ]
    }

});