/*
 * File: app/model/Payment2.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Payback.model.Payment2', {
    extend: 'Ext.data.Model',

    uses: [
        'Payback.model.Debt2'
    ],

    config: {
        identifier: {
            type: 'uuid'
        },
        fields: [
            {
                name: 'id',
                type: 'auto'
            },
            {
                name: 'debt_id'
            },
            {
                name: 'amount',
                type: 'float'
            },
            {
                name: 'date',
                type: 'date'
            },
            {
                name: 'memo',
                type: 'string'
            }
        ],
        proxy: {
            type: 'localstorage',
            id: 'Payments'
        },
        belongsTo: {
            model: 'Payback.model.Debt2',
            foreignKey: 'debt_id'
        }
    }
});