/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'Person',
        'Payment',
        'Debt',
        'Summary'
    ],
    stores: [
        'PeopleStore',
        'DebtsStore',
        'PaymentStore'
    ],
    views: [
        'DebtDetail',
        'Summary',
        'MainView',
        'myDebtListItem',
        'ContactDetail',
        'myContactListItem',
        'Debts',
        'Prey',
        'PaymentDetail',
        'myPaymentListItem'
    ],
    name: 'Payback',
    controllers: [
        'Contact',
        'Summary',
        'Debt',
        'Payment',
        'Routing'
    ],

    launch: function() {

        Ext.create('Payback.view.MainView', {fullscreen: true});
    }

});
