/*
 * File: app/controller/Debt.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Payback.controller.Debt', {
    extend: 'Ext.app.Controller',
    config: {
        refs: {
            DebtDetail: {
                selector: 'DebtDetail',
                xtype: 'DebtDetail',
                autoCreate: true
            },
            myDebtDataView: '#myDebtDataView',
            myPaymentDataView: '#myPaymentDataView',
            paymentButton: '#addPayment'
        },

        control: {
            "#addDebt": {
                tap: 'onAddDebtTap'
            },
            "#saveDebt": {
                tap: 'onSaveDebtTap'
            },
            "#cancelDebt": {
                tap: 'onCanelButtonTap'
            },
            "#myDebtDataView": {
                itemswipe: 'onDataviewItemSwipe',
                itemtap: 'onDataviewItemTap'
            }
        }
    },

    onAddDebtTap: function(button, e, options) {
        var form = this.getDebtDetail();
        form.reset();
        form.setRecord(null);

        Ext.getStore('Payments').clearFilter();

        this.getPaymentButton().hide();
        this.getMyPaymentDataView().hide();

        Ext.Viewport.setActiveItem(form);
    },

    onSaveDebtTap: function(button, e, options) {
        var form = this.getDebtDetail(),
            record = form.getRecord(),
            values = form.getValues(),
            person = this.getDebtDetail().down('selectfield').record;



        if(record) { //edit old record
            record.set(values);
            if (record.isModified('person_id')) {
                record.getPerson().debts().remove(record);
                record.setPerson(values.person_id);

                // The following two lines work around a bug that causes the Person instance not to be updated correctly
                delete record.PersonBelongsToInstance;
                record.getPerson(); // Sets up the Person instance reference again
            }
            record.set('balance',0);
            record.save();
        } else {  //new record 
            var debt = person.debts().add(values)[0];
            person.debts().sync();
            debt.getPerson(); //
        }


        person.calcBalance(); 


        Ext.getStore('Debts').load();

        Ext.getStore('People').load(function(){
            this.getApplication().getController('Summary').updateSummary();
        },
        this);

        Ext.Viewport.setActiveItem(0);

        //this.getMyDebtDataView().refresh();
    },

    onCanelButtonTap: function(button, e, options) {
        this.getDebtDetail().reset();

        var record = this.getDebtDetail().getRecord();
        if(record)
        record.set('balance',0); //calc balance

        Ext.Viewport.setActiveItem(0);
    },

    onDataviewItemSwipe: function(dataview, index, target, record, e, options) {
        var deleteButtons = dataview.query('button');

        for (var i=0; i < deleteButtons.length; i++) {
            deleteButtons[i].hide();
        }

        target.query('button')[0].show();

        Ext.Viewport.element.on({tap:function(){
            target.query('button')[0].hide();
        }, single:true});
    },

    onDataviewItemTap: function(dataview, index, target, record, e, options) {

        var form = this.getDebtDetail();
        form.setRecord(record);

        //debugger;

        Ext.getStore('Payments').clearFilter();
        Ext.getStore('Payments').filter({property: "debt_id", value: record.get('id')});

        this.getPaymentButton().show();
        this.getMyPaymentDataView().show();

        Ext.Viewport.setActiveItem(form);
    }

});