/*
 * File: app/controller/Payment.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Payback.controller.Payment', {
    extend: 'Ext.app.Controller',
    config: {
        stores: [
            'PaymentStore'
        ],

        refs: {
            PaymentDetail: {
                selector: 'PaymentDetail',
                xtype: 'PaymentDetail',
                autoCreate: true
            },
            DebtDetail: {
                selector: 'DebtDetail',
                xtype: 'DebtDetail',
                autoCreate: true
            }
        },

        control: {
            "#addPayment": {
                tap: 'onAddPaymentTap'
            },
            "#cancelPayment": {
                tap: 'onCancelButtonTap'
            },
            "#savePayment": {
                tap: 'onSavePaymentTap'
            },
            "#myPaymentDataView": {
                itemtap: 'onDataviewItemTap',
                itemswipe: 'onDataviewItemSwipe'
            }
        }
    },

    onAddPaymentTap: function(button, e, options) {

        var form = this.getPaymentDetail();

        form.reset();
        form.setRecord(null);

        form.setValues({debt_id:this.getDebtDetail().getRecord().get('id')});

        Ext.Viewport.setActiveItem(form);
    },

    onCancelButtonTap: function(button, e, options) {
        this.getPaymentDetail().reset();
        Ext.Viewport.setActiveItem(this.getDebtDetail());
    },

    onSavePaymentTap: function(button, e, options) {
        var form = this.getPaymentDetail(),
            record = form.getRecord(),
            values = form.getValues(),
            debt = this.getDebtDetail().getRecord();

        //console.log(values);

        if(record) {
            record.set(values);
            record.save();
        } else {    
            var payment = debt.payments().add(values)[0];
            debt.payments().sync();
            payment.getDebt();
        }



        //debt.calcBalance(); 
        //debt.getData(true);

        //debt.set('balance',0); //recalc balance

        Ext.getStore('Payments').load();

        //Ext.getStore('Debts').load();

        //Ext.getStore('Payments').filter({property: "debt_id", value: values.debt_id});

        //Ext.getStore('People').load(function(){ 
        //    this.getApplication().getController('Summary').updateSummary();
        //},
        //this);

        Ext.Viewport.setActiveItem(this.getDebtDetail());

    },

    onDataviewItemTap: function(dataview, index, target, record, e, options) {

        var form = this.getPaymentDetail();

        form.setRecord(record);

        Ext.Viewport.setActiveItem(form);
    },

    onDataviewItemSwipe: function(dataview, index, target, record, e, options) {
        var deleteButtons = dataview.query('button');

        for (var i=0; i < deleteButtons.length; i++) {
            deleteButtons[i].hide();
        }

        target.query('button')[0].show();

        Ext.Viewport.element.on({tap:function(){
            target.query('button')[0].hide();
        }, single:true});
    }

});