/*
 * File: app/controller/Summary.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Payback.controller.Summary', {
    extend: 'Ext.app.Controller',

    config: {
        models: [
            'Summary'
        ],
        summaryRecord: 0,

        routes: {
            'summary': 'showSummaryPanel'
        },

        refs: {
            SummaryContents: '#SummaryContents',
            MainView: 'MainView'
        },

        control: {
            "MainView": {
                activeitemchange: 'onTabpanelActiveItemChange'
            }
        }
    },

    onTabpanelActiveItemChange: function(container, value, oldValue, options) {

        /*var views = this.getMainView().getInnerItems();

        switch(value) {
        case views[0]:
        console.log(0);
        this.redirectTo('summary');
        break;
        case views[1]:
        console.log(1);
        this.redirectTo('debts');
        break;
        case views[2]:
        console.log(2);
        this.redirectTo('prey');
        break;
        }

        //return false;*/
    },

    updateSummary: function() {
        this.getSummaryRecord().set({
            totalOwed: Ext.getStore('People').sum('balance')
        });
    },

    launch: function() {
        this.getSummaryContents().setRecord(this.getSummaryRecord());

        Ext.getStore('People').load(function(){
            this.updateSummary();

        }, this);
    },

    applySummaryRecord: function(summaryRecord) {
        //if summary doesn't exist
        if (!summaryRecord){
            summaryRecord = Ext.create('Payback.model.Summary');
        }
        return summaryRecord;
    },

    showSummaryPanel: function() {

        //switch to summary panel
        Ext.Viewport.getActiveItem().setActiveItem(0);
    }

});